spring:
  count : 8
  secretKey : "KafkaMicroservice"
  expiryTime : 5
  datasource:
    url: jdbc:postgresql://localhost:5432/kafkaDb
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql

server:
  port: 8080
